#!/bin/bash

CWD="$(pwd)"
WALL_DIR="$HOME/.config/wallpapers"
cd "$WALL_DIR" || exit 1

IFS=$'\n'
SELECTED=$(for a in *jpg *.png; do echo -en "$a\0icon\x1f$a\n" ; done | rofi -dmenu -p "")

echo "$SELECTED"
if [ -n "$SELECTED" ]; then
	setwall "$SELECTED"
fi

cd "$CWD" || exit

