"""Spotify, via spicetify.

spicetify patches the Spotify client's own bundle, so a theme here is two
files: `color.ini`, a fixed set of named slots the client's stylesheet already
references, and `user.css`, injected afterwards for anything the slots cannot
express - radii, surfaces, the scrollbar.

Colours in color.ini are bare hex with no leading `#`; spicetify substitutes
them into CSS variables itself and a `#` produces `##15121B`.

Applying is not automatic: `spicetify apply` rewrites files under
/opt/spotify, and a Spotify update replaces them, so it has to be re-run.
That is deliberately left to the user rather than done from the theme
generator - regenerating a palette should never modify an installed program.
"""

from __future__ import annotations

from ..color import Colour
from ..tokens import Tokens
from . import header


def _bare(colour: Colour) -> str:
    """spicetify wants RRGGBB, not #RRGGBB."""
    return colour.hex6.lstrip("#")


def colors(tokens: Tokens) -> str:
    """Themes/blackwall/color.ini - the slots the client already references."""
    t = tokens
    slots = (
        ("text", t.fg, "primary text"),
        ("subtext", t.muted.over(t.bg), "secondary text"),
        ("main", t.bg, "the window body"),
        ("main-elevated", t.bg.mix(t.fg, 0.07), "raised panels"),
        ("highlight", t.bg.mix(t.fg, 0.10), "row hover"),
        ("highlight-elevated", t.bg.mix(t.fg, 0.14), "raised hover"),
        ("sidebar", t.bg.mix(t.fg, 0.04), "the library rail"),
        ("player", t.bg.mix(t.fg, 0.06), "the transport bar"),
        ("card", t.bg.mix(t.fg, 0.08), "album and playlist tiles"),
        ("shadow", t.bg.darken(0.6), "under cards"),
        ("selected-row", t.accent, "the playing row"),
        ("button", t.accent, "primary action"),
        ("button-active", t.accent.mix(t.link, 0.4), "pressed"),
        ("button-disabled", t.faint.over(t.bg), "unavailable"),
        ("tab-active", t.bg.mix(t.fg, 0.12), "current tab"),
        ("notification", t.accent, "toast"),
        ("notification-error", t.bad, "error toast"),
        ("misc", t.link, "everything else"),
    )
    width = max(len(name) for name, _, _ in slots)
    body = "\n".join(
        f"{name:<{width}} = {_bare(c):<8} ; {what}" for name, c, what in slots
    )
    return header(";", "", tokens=tokens) + f"\n[base]\n{body}\n"


def user_css(tokens: Tokens) -> str:
    """Themes/blackwall/user.css - the parts color.ini has no slot for.

    Kept small on purpose. Spotify's class names are generated and change on
    every client update, so anything that targets them is a maintenance debt;
    these rules stick to element selectors and CSS variables the client
    defines itself, which survive far longer.
    """
    t = tokens
    return f"""/* blackwall - Spotify.
 * Generated by theme/blackwall-theme. Colours live in color.ini; this file
 * carries only what has no slot there.
 *
 * Deliberately class-name-free: Spotify's classes are build-generated hashes
 * that change with every client release, so a stylesheet full of them breaks
 * silently on update. Element selectors and the client's own CSS variables
 * are the parts that last.
 */

:root {{
  --bw-accent: {t.accent.hex6};
  --bw-radius-lg: {t.r_lg};
  --bw-radius-md: {t.r_md};
  --bw-radius-sm: {t.r_sm};
}}

/* The radius scale, applied to the shapes the client actually exposes. */
button,
a[role="button"] {{
  border-radius: var(--bw-radius-md) !important;
}}

img {{
  border-radius: var(--bw-radius-md);
}}

/* Round the artwork in the transport bar a step tighter than the cards - it is
   a small object, and r_lg on something that size reads as a circle. */
footer img {{
  border-radius: var(--bw-radius-sm) !important;
}}

/* The overlay scrollbar, same behaviour as everywhere else in the rice:
   present when reached for, invisible while reading. */
::-webkit-scrollbar {{
  width: 8px;
  height: 8px;
}}

::-webkit-scrollbar-track {{
  background: transparent;
}}

::-webkit-scrollbar-thumb {{
  background: {t.faint.css};
  border-radius: {t.r_pill};
  border: 2px solid transparent;
  background-clip: content-box;
}}

::-webkit-scrollbar-thumb:hover {{
  background: {t.muted.css};
  background-clip: content-box;
}}

/* Selection matches the rest of the rice rather than Spotify's green. */
::selection {{
  background: {t.accent_hi.css};
  color: {t.fg.hex6};
}}

/* Focus rings: the client draws a bright white outline by default. */
*:focus-visible {{
  outline: 2px solid {t.accent_edge.css} !important;
  outline-offset: 2px;
  border-radius: var(--bw-radius-sm);
}}
"""
