#!/bin/bash

# start swww if not running
pgrep swww-daemon >/dev/null || swww-daemon &

# start eww daemon if not running
pgrep eww >/dev/null || eww daemon &

# Wlogout
pgrep wlogout >/dev/null || wlgout &

# set wallpaper
swww img "$1" --transition-type grow --transition-duration 1

# generate colors
wallust run "$1"

# reload UI
pkill waybar && waybar &
eww reload
kitty @ set-colors --all ~/.config/kitty/colors.conf

# Gtk3 for thunar
gsettings set org.gnome.desktop.interface gtk-theme "wallust"
