#!/bin/bash

LAST_WALL="$(cat ~/.cache/last_wallpaper > /dev/null 2>&1 || echo "$HOME/.config/wallpapers/cyberpunk.png")"

pgrep awww-daemon >/dev/null || awww-daemon &

swww img "$LAST_WALL" \
  --transition-type any \
  --transition-duration 1

