-- blackwall - a colourscheme that follows the wallpaper.
--
-- The palette is generated by theme/blackwall-theme into
-- lua/custom/blackwall_palette.lua, so this scheme re-themes with the rest of
-- the rice whenever setwall runs. This file decides which colour goes where;
-- it never spells a hex value.
--
-- Nothing needs registering: lua/custom/utils/themes.lua builds its list from
-- `vim.fn.getcompletion('', 'color')`, which finds any file in colors/. So
-- this appears in the theme switcher next to the other ten on its own.

local ok, p = pcall(require, 'custom.blackwall_palette')
if not ok then
  vim.notify(
    'blackwall: palette missing - run theme/blackwall-theme',
    vim.log.levels.WARN
  )
  return
end

vim.cmd.highlight 'clear'
if vim.fn.exists 'syntax_on' == 1 then
  vim.cmd.syntax 'reset'
end
vim.o.termguicolors = true
vim.g.colors_name = 'blackwall'

local a = p.ansi

--- Only three roles carry accent: what you are on, what you can follow, and
--- what needs a decision. Everything else is a tier of foreground.
local groups = {
  -- ---- base ------------------------------------------------------------
  Normal = { fg = p.fg, bg = p.bg },
  NormalNC = { fg = p.muted, bg = p.bg },
  NormalFloat = { fg = p.fg, bg = p.raised },
  FloatBorder = { fg = p.edge, bg = p.raised },
  FloatTitle = { fg = p.accent, bg = p.raised, bold = true },
  Cursor = { fg = p.bg, bg = p.cursor },
  lCursor = { fg = p.bg, bg = p.cursor },
  CursorLine = { bg = p.raised },
  CursorColumn = { bg = p.raised },
  ColorColumn = { bg = p.raised },
  -- The line number you are on is the only bright one; the rest recede.
  LineNr = { fg = p.faint },
  CursorLineNr = { fg = p.accent, bold = true },
  SignColumn = { bg = p.bg },
  FoldColumn = { fg = p.faint, bg = p.bg },
  Folded = { fg = p.muted, bg = p.raised },
  VertSplit = { fg = p.edge },
  WinSeparator = { fg = p.edge },
  EndOfBuffer = { fg = p.bg },
  Conceal = { fg = p.faint },
  Directory = { fg = p.accent },
  Title = { fg = p.accent, bold = true },
  MatchParen = { fg = p.warn, bold = true },
  NonText = { fg = p.faint },
  SpecialKey = { fg = p.faint },
  Whitespace = { fg = p.sunken },
  Visual = { bg = p.selection },
  VisualNOS = { bg = p.selection },
  Search = { fg = p.bg, bg = p.warn },
  IncSearch = { fg = p.bg, bg = p.accent },
  CurSearch = { fg = p.bg, bg = p.accent },
  Substitute = { fg = p.bg, bg = p.bad },
  QuickFixLine = { bg = p.selection },
  WinBar = { fg = p.muted, bg = p.bg },
  WinBarNC = { fg = p.faint, bg = p.bg },

  -- ---- messages and prompts --------------------------------------------
  ErrorMsg = { fg = p.bad, bold = true },
  WarningMsg = { fg = p.warn },
  MoreMsg = { fg = p.accent },
  ModeMsg = { fg = p.muted, bold = true },
  Question = { fg = p.accent },
  MsgArea = { fg = p.muted },

  -- ---- statusline and tabs ---------------------------------------------
  StatusLine = { fg = p.muted, bg = p.raised },
  StatusLineNC = { fg = p.faint, bg = p.raised },
  TabLine = { fg = p.faint, bg = p.raised },
  TabLineFill = { bg = p.bg },
  TabLineSel = { fg = p.on_accent or p.bg, bg = p.accent, bold = true },

  -- ---- popup menu -------------------------------------------------------
  Pmenu = { fg = p.muted, bg = p.raised },
  PmenuSel = { fg = p.fg, bg = p.selection, bold = true },
  PmenuSbar = { bg = p.raised_hi },
  PmenuThumb = { bg = p.faint },
  PmenuKind = { fg = p.link, bg = p.raised },
  PmenuExtra = { fg = p.faint, bg = p.raised },
  WildMenu = { fg = p.bg, bg = p.accent },

  -- ---- diff and git ------------------------------------------------------
  DiffAdd = { fg = p.good, bg = p.raised },
  DiffChange = { fg = p.warn, bg = p.raised },
  DiffDelete = { fg = p.bad, bg = p.raised },
  DiffText = { fg = p.fg, bg = p.selection, bold = true },
  Added = { fg = p.good },
  Changed = { fg = p.warn },
  Removed = { fg = p.bad },
  GitSignsAdd = { fg = p.good },
  GitSignsChange = { fg = p.warn },
  GitSignsDelete = { fg = p.bad },

  -- ---- syntax -------------------------------------------------------------
  -- The ANSI colours carry syntax, so a wallpaper's own hues show up in code
  -- rather than the whole file being one accent with grey around it.
  Comment = { fg = p.faint, italic = true },
  Constant = { fg = a[3] },
  String = { fg = a[2] },
  Character = { fg = a[2] },
  Number = { fg = a[3] },
  Boolean = { fg = a[3] },
  Float = { fg = a[3] },
  Identifier = { fg = p.fg },
  Function = { fg = p.accent },
  Statement = { fg = a[5] },
  Conditional = { fg = a[5] },
  Repeat = { fg = a[5] },
  Label = { fg = a[5] },
  Operator = { fg = p.muted },
  Keyword = { fg = a[5] },
  Exception = { fg = p.bad },
  PreProc = { fg = a[4] },
  Include = { fg = a[5] },
  Define = { fg = a[5] },
  Macro = { fg = a[4] },
  Type = { fg = a[4] },
  StorageClass = { fg = a[5] },
  Structure = { fg = a[4] },
  Typedef = { fg = a[4] },
  Special = { fg = p.link },
  SpecialChar = { fg = p.link },
  Delimiter = { fg = p.muted },
  Tag = { fg = p.link },
  Debug = { fg = p.warn },
  Underlined = { fg = p.link, underline = true },
  Error = { fg = p.bad, bold = true },
  Todo = { fg = p.bg, bg = p.warn, bold = true },

  -- ---- diagnostics ---------------------------------------------------------
  DiagnosticError = { fg = p.bad },
  DiagnosticWarn = { fg = p.warn },
  DiagnosticInfo = { fg = p.link },
  DiagnosticHint = { fg = p.accent },
  DiagnosticOk = { fg = p.good },
  DiagnosticUnderlineError = { sp = p.bad, undercurl = true },
  DiagnosticUnderlineWarn = { sp = p.warn, undercurl = true },
  DiagnosticUnderlineInfo = { sp = p.link, undercurl = true },
  DiagnosticUnderlineHint = { sp = p.accent, undercurl = true },
  DiagnosticVirtualTextError = { fg = p.bad, bg = p.raised },
  DiagnosticVirtualTextWarn = { fg = p.warn, bg = p.raised },
  DiagnosticVirtualTextInfo = { fg = p.link, bg = p.raised },
  DiagnosticVirtualTextHint = { fg = p.accent, bg = p.raised },

  -- ---- LSP -----------------------------------------------------------------
  LspReferenceText = { bg = p.raised_hi },
  LspReferenceRead = { bg = p.raised_hi },
  LspReferenceWrite = { bg = p.raised_hi, underline = true },
  LspInlayHint = { fg = p.faint, bg = p.raised },
  LspSignatureActiveParameter = { fg = p.accent, bold = true },

  -- ---- treesitter -----------------------------------------------------------
  ['@variable'] = { fg = p.fg },
  ['@variable.builtin'] = { fg = a[5], italic = true },
  ['@variable.parameter'] = { fg = p.muted },
  ['@variable.member'] = { fg = p.fg },
  ['@constant'] = { fg = a[3] },
  ['@constant.builtin'] = { fg = a[3], italic = true },
  ['@module'] = { fg = a[4] },
  ['@string'] = { fg = a[2] },
  ['@string.escape'] = { fg = p.link },
  ['@string.special.url'] = { fg = p.link, underline = true },
  ['@function'] = { fg = p.accent },
  ['@function.builtin'] = { fg = p.accent, italic = true },
  ['@function.method'] = { fg = p.accent },
  ['@constructor'] = { fg = a[4] },
  ['@keyword'] = { fg = a[5] },
  ['@keyword.return'] = { fg = a[5], bold = true },
  ['@type'] = { fg = a[4] },
  ['@type.builtin'] = { fg = a[4], italic = true },
  ['@property'] = { fg = p.fg },
  ['@punctuation'] = { fg = p.muted },
  ['@punctuation.bracket'] = { fg = p.muted },
  ['@punctuation.delimiter'] = { fg = p.muted },
  ['@comment'] = { fg = p.faint, italic = true },
  ['@comment.error'] = { fg = p.bg, bg = p.bad, bold = true },
  ['@comment.warning'] = { fg = p.bg, bg = p.warn, bold = true },
  ['@comment.todo'] = { fg = p.bg, bg = p.accent, bold = true },
  ['@comment.note'] = { fg = p.bg, bg = p.link, bold = true },
  ['@markup.heading'] = { fg = p.accent, bold = true },
  ['@markup.link'] = { fg = p.link, underline = true },
  ['@markup.raw'] = { fg = a[2] },
  ['@markup.list'] = { fg = p.muted },
  ['@diff.plus'] = { fg = p.good },
  ['@diff.minus'] = { fg = p.bad },
  ['@tag'] = { fg = a[5] },
  ['@tag.attribute'] = { fg = a[4] },
  ['@tag.delimiter'] = { fg = p.muted },

  -- ---- telescope --------------------------------------------------------------
  -- The switcher itself runs in telescope, so this is the first thing seen.
  TelescopeNormal = { fg = p.fg, bg = p.raised },
  TelescopeBorder = { fg = p.edge, bg = p.raised },
  TelescopeTitle = { fg = p.accent, bold = true },
  TelescopePromptNormal = { fg = p.fg, bg = p.raised_hi },
  TelescopePromptBorder = { fg = p.raised_hi, bg = p.raised_hi },
  TelescopePromptTitle = { fg = p.bg, bg = p.accent, bold = true },
  TelescopePromptPrefix = { fg = p.accent, bg = p.raised_hi },
  TelescopeSelection = { fg = p.fg, bg = p.selection, bold = true },
  TelescopeSelectionCaret = { fg = p.accent, bg = p.selection },
  TelescopeMatching = { fg = p.warn, bold = true },
  TelescopeResultsComment = { fg = p.faint },

  -- ---- common plugins ------------------------------------------------------
  NvimTreeNormal = { fg = p.muted, bg = p.bg },
  NvimTreeFolderIcon = { fg = p.accent },
  NvimTreeRootFolder = { fg = p.accent, bold = true },
  NvimTreeGitDirty = { fg = p.warn },
  NvimTreeGitNew = { fg = p.good },
  NvimTreeGitDeleted = { fg = p.bad },
  NvimTreeIndentMarker = { fg = p.edge },
  WhichKey = { fg = p.accent },
  WhichKeyGroup = { fg = p.link },
  WhichKeyDesc = { fg = p.fg },
  WhichKeySeparator = { fg = p.faint },
  WhichKeyFloat = { bg = p.raised },
  IndentBlanklineChar = { fg = p.sunken },
  IblIndent = { fg = p.sunken },
  IblScope = { fg = p.edge },
  CmpItemAbbr = { fg = p.muted },
  CmpItemAbbrMatch = { fg = p.accent, bold = true },
  CmpItemKind = { fg = p.link },
  CmpItemMenu = { fg = p.faint },
  NotifyERRORBorder = { fg = p.bad },
  NotifyWARNBorder = { fg = p.warn },
  NotifyINFOBorder = { fg = p.link },
  NotifyDEBUGBorder = { fg = p.faint },
  NotifyTRACEBorder = { fg = p.accent },
}

for group, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, group, spec)
end

-- Terminal colours inside :terminal, so a shell in a split matches kitty.
for i = 0, 15 do
  vim.g['terminal_color_' .. i] = a[i]
end
