#!/bin/bash

if pgrep -x hyprsunset >/dev/null; then
	pkill hyprsunset
	eww update nightmode=false
	notify-send "Night Light Off"
else
	hyprsunset -t 3000 &
	eww update nightmode=true
	notify-send "Night Light On"
fi

