backend = "full"
color_space = "lab"
palette = "dark"
threshold = 10

[templates.waybar]
template = "/home/scriptkid/.config/wallust/templates/waybar.css"
target   = "/home/scriptkid/.config/waybar/colors.css"

[templates.eww]
template = "/home/scriptkid/.config/wallust/templates/eww.scss"
target   = "/home/scriptkid/.config/eww/colors.scss"

[templates.kitty]
template = "/home/scriptkid/.config/wallust/templates/kitty.conf"
target   = "/home/scriptkid/.config/kitty/colors.conf"

