backend = "full"
color_space = "lab"
palette = "dark"
threshold = 10

[templates.gtk3]
template = "/home/scriptkid/.config/wallust/templates/gtk3.css"
target = "/home/scriptkid/.themes/wallust/gtk-3.0/colors.css"

[templates.rofi]
template = "/home/scriptkid/.config/wallust/templates/rofi.rasi"
target = "/home/scriptkid/.config/rofi/colors/wallust.rasi"

[templates.wlogout]
template = "/home/scriptkid/.config/wallust/templates/wlogout.css"
target   = "/home/scriptkid/.config/wlogout/colors/colors.css"

[templates.waybar]
template = "/home/scriptkid/.config/wallust/templates/waybar.css"
target   = "/home/scriptkid/.config/waybar/colors.css"

[templates.eww]
template = "/home/scriptkid/.config/wallust/templates/eww.scss"
target   = "/home/scriptkid/.config/eww/colors.scss"

[templates.kitty]
template = "/home/scriptkid/.config/wallust/templates/kitty.conf"
target   = "/home/scriptkid/.config/kitty/colors.conf"

