backend = "full"
color_space = "lab"
palette = "dark"
threshold = 10

[templates.rofi]
template = "rofi.rasi"
target = "~/.config/rofi/colors/wallust.rasi"

[templates.wlogout]
template = "wlogout.css"
target   = "~/.config/wlogout/colors/colors.css"

[templates.waybar]
template = "waybar.css"
target   = "~/.config/waybar/colors.css"

[templates.eww]
template = "eww.scss"
target   = "~/.config/eww/colors.scss"

[templates.palette]
template = "palette.json"
target = "~/.cache/blackwall/palette.json"
