#!/usr/bin/env bash

iface=$(ip route show default | awk '{print $5; exit}')

rx1=$(cat /sys/class/net/"$iface"/statistics/rx_bytes)
sleep 1
rx2=$(cat /sys/class/net/"$iface"/statistics/rx_bytes)

speed=$(( (rx2 - rx1) / 1024 ))   # KB/s

# 0-10 => 1 bar, 10-20 => 2 bars, etc
level=$(( speed / 10 ))
[ "$level" -lt 1 ] && level=1
[ "$level" -gt 8 ] && level=8

active=("▂" "▄" "▆" "▇")
bars=("▂" "▄" "▆" "▇")

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd -- "$SCRIPT_DIR/../.." && pwd)"
activeColor=$(grep -oP '\$fg:\s*\K[^;]+' "colors.scss")
color=$(grep -oP '\$accent:\s*\K[^;]+' "colors.scss")

out=""
space=" "
for ((i=0; i<4; i++)); do
  if [ "$i" -le "$level" ]; then
	  out+="<span foreground='${activeColor}'>${active[$i]}</span><span>${space}</span>"
  else
	  out+="<span foreground='${color}'>${bars[$i]}</span><span>${space}</span>"
  fi
done

# bigger/taller via font size
echo "<span font_size='18000'>$out</span>"
