"""A compact description of this machine, for the system prompt.

Kept deliberately small. It rides in `--append-system-prompt`, which sits in the
prompt-cached prefix, so it is paid for once per session rather than per turn -
but a long block still crowds the real instructions and dilutes them. The bar
for a line here is: the model would otherwise guess wrong, and guessing wrong
costs a tool call.

Versions are read live rather than hardcoded so this cannot go stale.
"""

from __future__ import annotations

import platform
import shutil
import subprocess

from .. import paths


def _version(binary: str, *args: str) -> str:
    if not shutil.which(binary):
        return ""
    try:
        out = subprocess.run([binary, *args], capture_output=True, text=True,
                             timeout=3, check=False)
    except (OSError, subprocess.SubprocessError):
        return ""
    text = (out.stdout or out.stderr).strip().splitlines()
    if not text:
        return ""
    import re
    found = re.search(r"\d+\.\d+(\.\d+)?", text[0])
    return found.group(0) if found else ""


def _present(*names: str) -> list[str]:
    return [n for n in names if shutil.which(n)]


def describe() -> str:
    hypr = _version("hyprctl", "version")
    eww = _version("eww", "--version")
    tools = _present("wallust", "mako", "waybar", "rofi", "kitty", "hyprlock",
                     "hypridle", "swww", "awww", "thunar", "nvim", "tmux", "fish")

    return f"""\
<machine>
Arch Linux, kernel {platform.release()}, Wayland/Hyprland {hypr or "?"}. Shell: fish.
Rice lives in {paths.DOTFILES} (git repo, "blackwall"), symlinked into ~/.config.
  hypr/configs/*.conf   sourced by hypr/hyprland.conf (keybinds, windowrules, ...)
  eww/  eww {eww or "?"} bar/widgets: widgets/*.yuck + scss/*.scss, entry eww.yuck + eww.scss
  waybar/  config + modules/*.json + style.css      rofi/  launchers/type-N/style-N.rasi
  fish/  kitty/  mako/  nvim/  tmux/  wallust/  wallpapers/  scripts/
Colours are generated by wallust from the wallpaper into eww/colors.scss,
waybar/colors.css and rofi launcher shared/colors.rasi - edit the wallust
templates, not the generated files.
Present: {", ".join(tools)}.
Prefer hyprctl/systemctl --user/pacman. Edits under the rice are git-tracked and
auto-committed, so they are revertable; edits elsewhere are not.
</machine>"""
