#!/bin/bash

magick icons/lock.png      -channel RGB -negate icons/lock-white.png
magick icons/logout.png    -channel RGB -negate icons/logout-white.png
magick icons/sleep.png     -channel RGB -negate icons/sleep-white.png
magick icons/reboot.png    -channel RGB -negate icons/reboot-white.png
magick icons/power.png     -channel RGB -negate icons/power-white.png
magick icons/hibernate.png -channel RGB -negate icons/hibernate-white.png
