#!/bin/bash

echo "$1" > ~/.cache/last_wallpaper

# start awww if not running
pgrep awww-daemon >/dev/null || awww-daemon &

# start eww daemon if not running
pgrep eww >/dev/null || eww daemon &

# Wlogout
pgrep wlogout >/dev/null || wlgout &

# set wallpaper
awww img "$1" --transition-type grow --transition-duration 1

# generate colors
wallust run "$1"

# reload UI
pkill waybar && waybar &
eww reload
kitty @ set-colors --all ~/.config/kitty/colors.conf

# Gtk3 for thunar
gsettings set org.gnome.desktop.interface gtk-theme "wallust"
