import json

from archpilot.context.history import CONTEXT_CLOSE, CONTEXT_OPEN, is_noise, recent, strip_context


def user(text):
    return {"type": "user", "cwd": "/home/u/dev",
            "message": {"role": "user", "content": [{"type": "text", "text": text}]}}


def write(root, project, session, records):
    d = root / project
    d.mkdir(parents=True, exist_ok=True)
    p = d / f"{session}.jsonl"
    p.write_text("\n".join(json.dumps(r) for r in records) + "\n")
    return p


def test_injected_context_is_stripped_from_the_prompt():
    raw = f"{CONTEXT_OPEN}\nFocused window: kitty\n{CONTEXT_CLOSE}\n\nwhy did that fail?"
    assert strip_context(raw) == "why did that fail?"


def test_text_without_context_survives():
    assert strip_context("plain question") == "plain question"


def test_skill_bodies_are_not_history():
    assert is_noise("Base directory for this skill: /tmp/x")
    assert is_noise("<command-name>/loop</command-name>")
    assert is_noise("Caveat: The messages below were generated by")


def test_real_prompts_are_not_noise():
    assert not is_noise("how much ram is used?")
    assert not is_noise("continue")


def test_recent_returns_user_prompts_newest_first(tmp_path):
    write(tmp_path, "-p", "s1", [user("first question"), user("second question")])
    prompts = [e.prompt for e in recent(root=tmp_path)]
    assert prompts[0] == "second question"
    assert "first question" in prompts


def test_duplicates_are_collapsed(tmp_path):
    write(tmp_path, "-p", "s1", [user("same"), user("same"), user("other")])
    prompts = [e.prompt for e in recent(root=tmp_path)]
    assert prompts.count("same") == 1


def test_noise_is_excluded_from_results(tmp_path):
    write(tmp_path, "-p", "s1", [user("Base directory for this skill: /x"), user("real one")])
    assert [e.prompt for e in recent(root=tmp_path)] == ["real one"]


def test_context_block_is_stripped_in_results(tmp_path):
    write(tmp_path, "-p", "s1",
          [user(f"{CONTEXT_OPEN}\nnoise\n{CONTEXT_CLOSE}\n\nthe actual prompt")])
    assert [e.prompt for e in recent(root=tmp_path)] == ["the actual prompt"]


def test_limit_is_respected(tmp_path):
    write(tmp_path, "-p", "s1", [user(f"q{i}") for i in range(50)])
    assert len(recent(limit=5, root=tmp_path)) == 5


def test_missing_root_is_not_fatal(tmp_path):
    assert recent(root=tmp_path / "nope") == []


def test_archpilots_own_generated_prompts_are_not_history():
    """Offering to re-run a prompt the user never typed is confusing."""
    assert is_noise("Run exactly this command and report the result. Do not modify it.\n\nls")
    assert is_noise("These systemd units are failed: mako.service. Look at their status")


def test_a_user_prompt_that_merely_mentions_running_is_kept():
    assert not is_noise("how do I run this command in fish?")
