"""Generate a self-contained rofi theme from the rice's colours.

Two reasons this exists rather than pointing at one of the launcher themes:

* Those themes `@import "shared/colors.rasi"`, and that file is missing on this
  machine - it is generated by wallust and was never produced. rofi then fails
  every variable lookup and falls back to its unstyled default.
* Generating from `eww/colors.scss` means the picker re-themes with the rest of
  the rice when the wallpaper changes, with no second place to keep in sync.
"""

from __future__ import annotations

import re
from pathlib import Path

from . import paths

COLORS_SCSS = paths.DOTFILES / "eww" / "colors.scss"

FALLBACK = {"bg": "#251F2B", "fg": "#F7ECFF", "accent": "#5A92C5"}

_VAR = re.compile(r"^\s*\$(\w+)\s*:\s*(#[0-9a-fA-F]{3,8})\s*;?\s*$", re.MULTILINE)

TEMPLATE = """\
/* Generated by archpilot from eww/colors.scss. Do not edit by hand. */
* {{
    bg:      {bg};
    fg:      {fg};
    accent:  {accent};
    bg-alt:  {bg_alt};
    muted:   {muted};

    background-color: transparent;
    text-color:       @fg;
    font:             "JetBrainsMono Nerd Font 11";
}}

window {{
    transparency:     "real";
    location:         center;
    width:            46%;
    border-radius:    14px;
    border:           1px;
    border-color:     @accent;
    background-color: @bg;
    padding:          18px;
}}

mainbox {{ children: [ inputbar, listview ]; spacing: 12px; }}

inputbar {{
    background-color: @bg-alt;
    border-radius:    10px;
    padding:          10px 12px;
    children:         [ prompt, entry ];
    spacing:          10px;
}}

prompt {{ text-color: @accent; }}
entry  {{ placeholder: "search"; placeholder-color: @muted; cursor: text; }}

listview {{
    lines:         12;
    columns:       1;
    scrollbar:     false;
    fixed-height:  false;
    spacing:       4px;
}}

element {{ padding: 8px 10px; border-radius: 8px; cursor: pointer; }}
element normal.normal   {{ text-color: @fg; }}
element alternate.normal{{ text-color: @fg; }}
element selected.normal {{ background-color: @accent; text-color: @bg; }}
element-text {{ background-color: inherit; text-color: inherit; }}
"""


def _read_colors() -> dict[str, str]:
    try:
        text = COLORS_SCSS.read_text()
    except OSError:
        return dict(FALLBACK)
    found = {name: value for name, value in _VAR.findall(text)}
    return {key: found.get(key, FALLBACK[key]) for key in FALLBACK}


def _mix(hex_a: str, hex_b: str, weight: float) -> str:
    """Blend two #rrggbb colours; used for the derived alt/muted shades."""
    def parts(value: str) -> tuple[int, int, int]:
        value = value.lstrip("#")
        if len(value) == 3:
            value = "".join(c * 2 for c in value)
        return tuple(int(value[i:i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]

    a, b = parts(hex_a), parts(hex_b)
    blended = tuple(round(x + (y - x) * weight) for x, y in zip(a, b))
    return "#%02X%02X%02X" % blended


def render() -> Path:
    """Write the theme into the runtime dir and return its path."""
    colors = _read_colors()
    body = TEMPLATE.format(
        bg=colors["bg"],
        fg=colors["fg"],
        accent=colors["accent"],
        bg_alt=_mix(colors["bg"], colors["fg"], 0.10),
        muted=_mix(colors["bg"], colors["fg"], 0.55),
    )
    target = paths.runtime_dir() / "archpilot-rofi.rasi"
    target.write_text(body)
    return target


# --------------------------------------------------------------------------
# Repairing the rice's own launcher themes.
# --------------------------------------------------------------------------

#: Every launcher theme here derives its palette from these six variables and
#: expects them in shared/colors.rasi. That file is generated by wallust and is
#: absent on this machine, so rofi fails ~45 lookups and silently renders
#: unstyled - which is why SUPER+R / SUPER+F / SUPER+U have no theme.
LAUNCHERS = paths.DOTFILES / "rofi" / "launchers"

LAUNCHER_COLORS = """\
/**
 * Generated by archpilot from eww/colors.scss (wallust output).
 * The launcher themes derive their whole palette from these six variables.
 */

* {{
    background:     {bg}FF;
    background-alt: {bg_alt}FF;
    foreground:     {fg}FF;
    selected:       {accent}FF;
    active:         {active}FF;
    urgent:         {urgent}FF;
}}
"""


def sync_launcher_colors() -> list[Path]:
    """Write shared/colors.rasi for every launcher type that expects one.

    Idempotent, and derived from the same palette as everything else, so the
    launchers re-theme when the wallpaper does. Returns the files written.
    """
    if not LAUNCHERS.is_dir():
        return []

    colors = _read_colors()
    body = LAUNCHER_COLORS.format(
        bg=colors["bg"],
        fg=colors["fg"],
        accent=colors["accent"],
        bg_alt=_mix(colors["bg"], colors["fg"], 0.10),
        active=_mix(colors["accent"], colors["fg"], 0.35),
        urgent=_mix(colors["accent"], "#FF4D4D", 0.60),
    )

    written = []
    for shared in sorted(LAUNCHERS.glob("type-*/shared")):
        if not shared.is_dir():
            continue
        target = shared / "colors.rasi"
        try:
            if target.exists() and target.read_text() == body:
                continue
            target.write_text(body)
            written.append(target)
        except OSError:
            continue
    return written
