exec-once = busctl -j --user call org.freedesktop.Notifications /fr/emersion/Mako fr.emersion.Mako -- ListNotifications
# --- notifications
exec-once = mako

# --- wallpaper daemon
exec-once = setwall /home/scriptkid/sddm-astronaut-theme/Backgrounds/black_hole.png

# --- bar
exec-once = waybar 

# --- eww (daemon only; widgets launched separately)
exec-once = eww daemon

exec-once = wl-clipboard-history -t

# exec-once = hypridle

exec-once = wayvnc -R -v -L debug 127.0.0.1 5900
exec-once = xfsettingsd
