exec-once = systemctl --user start pipewire pipewire-pulse wireplumber
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# --- notifications
exec-once = mako

# --- wallpaper daemon
exec-once = swww-daemon
exec-once = sleep 2 && swww img /home/scriptkid/.config/.dotfiles/blackwall/tokyo/TokyoNight.png

# --- bar
exec-once = waybar 

# --- Wallpaper
exec-once = hyprpaper

# --- eww (daemon only; widgets launched separately)
exec-once = eww daemon

exec-once = wl-clipboard-history -t
exec-once = hypridle

