windowrule = match:class ^(eww-my-sticker-window)$, float on
windowrule = match:class ^(eww-my-sticker-window)$, pin on


# Safety limits so you can safely drag and resize with your mouse


windowrule = min_size 150 100, match:class ^(eww-my-sticker-window)$
windowrule = max_size 600 800, match:class ^(eww-my-sticker-window)$
