
windowrulev2 = opacity 0.92 0.88, class:(.*)
# wlogout often uses these namespaces depending on how it’s launched
layerrule = blur on, ignore_alpha 0.05, dim_around on, match:namespace logout_dialog
layerrule = blur on, ignore_alpha 0.05, dim_around on, match:namespace gtk-layer-shell
