# Wlogout
windowrulev2 = opacity 0.92 0.88, class:(.*)
layerrule = blur on, ignore_alpha 0.05, dim_around on, match:namespace logout_dialog
layerrule = blur on, ignore_alpha 0.05, dim_around on, match:namespace gtk-layer-shell

layerrule = blur on, ignore_alpha 0, dim_around on, match:namespace eww_ios
layerrule = blur off, match:namespace eww_calendar

# # Exclude Opacities
windowrule = match:class ^(zen|firefox|Wlogout)$, opacity 1.0 override

# # Popups Floating
windowrule = match:tag portal-dialogs, size 50 60
windowrule = match:tag portal-dialogs, float true
windowrule = match:tag portal-dialogs, center on

windowrule = match:class ^(xdg-desktop-portal-gtk)$, float on
windowrule = match:class ^(xdg-desktop-portal-gtk)$, center on
windowrule = match:class ^(xdg-desktop-portal-gtk)$, size 1000 750

windowrule = match:class ^(xdg-desktop-portal-hyprland)$, float on
windowrule = match:class ^(xdg-desktop-portal-hyprland)$, float on
windowrule = match:class ^(xdg-desktop-portal-hyprland)$, center on

windowrule = match:class ^(xdg-desktop-portal-kde)$, float on
windowrule = match:class ^(xdg-desktop-portal-kde)$, center on
windowrule = match:class ^(xdg-desktop-portal-kde)$, size 1000 750


# # Waydroid
# windowrulev2 = float, class:^(Waydroid)$
# windowrulev2 = size 800 600, class:^(Waydroid)$
# windowrulev2 = center, class:^(Waydroid)$
windowrulev2 = fullscreen, class:^(Waydroid)$

